name: gas
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.18
  - pip
  - pip:
    - "--extra-index-url=https://download.pytorch.org/whl/cu124"
    - torch==2.4.0 
    - torchvision==0.19.0 
    - torchaudio==2.4.0
    - matplotlib==3.7.5
    - lpips==0.1.4
    - ml_collections==0.1.1
    - torch-ema==0.3
    - wandb==0.15.7
    - omegaconf==2.1.1
    - einops==0.3.0
    - pytorch-lightning==1.4.2
    - torchmetrics==0.6.0
    - transformers==4.40.1
    - packaging==21.3
    - kornia==0.5.0
    - ftfy==6.2.3
    - ninja==1.10.2
  - nvidia/label/cuda-12.4.0::cuda-nvcc
  - nvidia/label/cuda-12.4.0::cuda-cudart
  - nvidia/label/cuda-12.4.0::cuda-cudart-dev
  - nvidia/label/cuda-12.4.0::libcusparse
  - nvidia/label/cuda-12.4.0::libcublas-dev
  - nvidia/label/cuda-12.4.0::cuda-toolkit
  - nvidia/label/cuda-12.4.0::libcusolver-dev
  - libxcrypt=4.4.36
